export {
  FaSearch as SearchIcon,
  FaTimes as CloseIcon,
  FaChevronDown as ChevronDownIcon,
  FaChevronUp as ChevronUpIcon,
  FaChevronLeft as ChevronLeftIcon,
  FaChevronRight as ChevronRightIcon,
  FaStar as StarIcon,
  FaHeart as HeartIcon,
  FaRegHeart as HeartOutlineIcon,
  FaTrash as TrashIcon,
  FaExternalLinkAlt as ExternalLinkIcon,
  FaSpinner as SpinnerIcon,
  FaExclamationTriangle as WarningIcon,
  FaRedo as RetryIcon,
} from 'react-icons/fa'
